# Project: Project1
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Untitled2.o
LINKOBJ  = main.o Untitled2.o
LIBS     = -L"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Anastasia/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Untitled2.o: Untitled2.cpp
	$(CPP) -c Untitled2.cpp -o Untitled2.o $(CXXFLAGS)
